name: Run WTM Exhibitor Scraper

on:
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 3:00 AM UTC (~8:30 AM IST)
  workflow_dispatch:      # Allows manual run from GitHub Actions tab

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python wtm_scraper.py

      - name: Commit and push updated file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto update exhibitor list"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
